## 19.4.2 DeepLearning_Tabular

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('Resources/HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

## 19.4.3 Real Data, Real Practice Preprocessing

In [3]:
# Check the number of unique values in each column.
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [7]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## 19.4.4 Real Data, Real Practice Deep Learning Model Design

In [8]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [9]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

## 19.4.5 Real Data, Real Practice Train and Evaluate the Model

In [10]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 0s 770us/step - loss: 385.6817 - accuracy: 0.8122
Epoch 2/100
35/35 [==============================] - 0s 690us/step - loss: 152.9973 - accuracy: 0.6878
Epoch 3/100
35/35 [==============================] - 0s 687us/step - loss: 84.7207 - accuracy: 0.6779
Epoch 4/100
35/35 [==============================] - 0s 751us/step - loss: 69.2695 - accuracy: 0.7232
Epoch 5/100
35/35 [==============================] - 0s 721us/step - loss: 56.6224 - accuracy: 0.7187
Epoch 6/100
35/35 [==============================] - 0s 768us/step - loss: 47.3846 - accuracy: 0.7214
Epoch 7/100
35/35 [==============================] - 0s 754us/step - loss: 38.2071 - accuracy: 0.7178
Epoch 8/100
35/35 [==============================] - 0s 804us/step - loss: 31.9716 - accuracy: 0.7441
Epoch 9/100
35/35 [==============================] - 0s 744us/step - loss: 23.9151 - accuracy: 0.7577
Epoch 10/100
35/35 [==============================] - 0s 943us/step - loss: 18.0140 - accuracy: 0.7387
Epoch 11/100
35/35 [==============================] - 0s 910us/step - loss: 11.7202 - accuracy: 0.7523
Epoch 12/100
35/35 [==============================] - 0s 773us/step - loss: 9.9522 - accuracy: 0.7532
Epoch 13/100
35/35 [==============================] - 0s 786us/step - loss: 5.4662 - accuracy: 0.7559
Epoch 14/100
35/35 [==============================] - 0s 715us/step - loss: 3.4066 - accuracy: 0.7550
Epoch 15/100
35/35 [==============================] - 0s 733us/step - loss: 2.2898 - accuracy: 0.7477
Epoch 16/100
35/35 [==============================] - 0s 752us/step - loss: 3.5028 - accuracy: 0.7296
Epoch 17/100
35/35 [==============================] - 0s 743us/step - loss: 1.7934 - accuracy: 0.7632
Epoch 18/100
35/35 [==============================] - 0s 756us/step - loss: 1.9123 - accuracy: 0.7477
Epoch 19/100
35/35 [==============================] - 0s 806us/step - loss: 3.0236 - accuracy: 0.7514
Epoch 20/100
35/35 [==============================] - 0s 782us/step - loss: 1.6734 - accuracy: 0.7613
Epoch 21/100
35/35 [==============================] - 0s 864us/step - loss: 1.8361 - accuracy: 0.7423
Epoch 22/100
35/35 [==============================] - 0s 815us/step - loss: 1.4972 - accuracy: 0.7495
Epoch 23/100
35/35 [==============================] - 0s 771us/step - loss: 3.1670 - accuracy: 0.7586
Epoch 24/100
35/35 [==============================] - 0s 804us/step - loss: 1.0324 - accuracy: 0.7731
Epoch 25/100
35/35 [==============================] - 0s 817us/step - loss: 1.0087 - accuracy: 0.7659
Epoch 26/100
35/35 [==============================] - 0s 876us/step - loss: 1.3659 - accuracy: 0.7523
Epoch 27/100
35/35 [==============================] - 0s 821us/step - loss: 1.6136 - accuracy: 0.7641
Epoch 28/100
35/35 [==============================] - 0s 719us/step - loss: 4.4181 - accuracy: 0.7486
Epoch 29/100
35/35 [==============================] - 0s 772us/step - loss: 3.5718 - accuracy: 0.7459
Epoch 30/100
35/35 [==============================] - 0s 886us/step - loss: 1.1438 - accuracy: 0.7559
Epoch 31/100
35/35 [==============================] - 0s 819us/step - loss: 1.9434 - accuracy: 0.7541
Epoch 32/100
35/35 [==============================] - 0s 801us/step - loss: 1.8537 - accuracy: 0.7523
Epoch 33/100
35/35 [==============================] - 0s 793us/step - loss: 1.5232 - accuracy: 0.7677
Epoch 34/100
35/35 [==============================] - 0s 714us/step - loss: 1.1063 - accuracy: 0.7641
Epoch 35/100
35/35 [==============================] - 0s 828us/step - loss: 2.6828 - accuracy: 0.7532
Epoch 36/100
35/35 [==============================] - 0s 815us/step - loss: 2.6077 - accuracy: 0.7414
Epoch 37/100
35/35 [==============================] - 0s 839us/step - loss: 1.1982 - accuracy: 0.7704
Epoch 38/100
35/35 [==============================] - 0s 771us/step - loss: 0.7204 - accuracy: 0.8076
Epoch 39/100
35/35 [==============================] - 0s 808us/step - loss: 1.0300 - accuracy: 0.7777
Epoch 40/100
35/35 [==============================] - 0s 796us/step - loss: 1.5797 - accuracy: 0.7613
Epoch 41/100
35/35 [==============================] - 0s 744us/step - loss: 0.9631 - accuracy: 0.7958
Epoch 42/100
35/35 [==============================] - 0s 786us/step - loss: 1.6158 - accuracy: 0.7550
Epoch 43/100
35/35 [==============================] - 0s 779us/step - loss: 0.6428 - accuracy: 0.8131
Epoch 44/100
35/35 [==============================] - 0s 832us/step - loss: 1.8542 - accuracy: 0.7650
Epoch 45/100
35/35 [==============================] - 0s 785us/step - loss: 3.3184 - accuracy: 0.7396
Epoch 46/100
35/35 [==============================] - 0s 937us/step - loss: 1.7823 - accuracy: 0.7595
Epoch 47/100
35/35 [==============================] - 0s 947us/step - loss: 1.0503 - accuracy: 0.7786
Epoch 48/100
35/35 [==============================] - 0s 881us/step - loss: 1.8459 - accuracy: 0.7722
Epoch 49/100
35/35 [==============================] - 0s 832us/step - loss: 3.6144 - accuracy: 0.7523
Epoch 50/100
35/35 [==============================] - 0s 800us/step - loss: 0.8152 - accuracy: 0.7877
Epoch 51/100
35/35 [==============================] - 0s 771us/step - loss: 1.5625 - accuracy: 0.7523
Epoch 52/100
35/35 [==============================] - 0s 842us/step - loss: 1.2804 - accuracy: 0.7550
Epoch 53/100
35/35 [==============================] - 0s 916us/step - loss: 1.0373 - accuracy: 0.7759
Epoch 54/100
35/35 [==============================] - 0s 977us/step - loss: 1.9446 - accuracy: 0.7641
Epoch 55/100
35/35 [==============================] - 0s 756us/step - loss: 1.2800 - accuracy: 0.7967
Epoch 56/100
35/35 [==============================] - 0s 878us/step - loss: 1.5897 - accuracy: 0.7858
Epoch 57/100
35/35 [==============================] - 0s 865us/step - loss: 0.9758 - accuracy: 0.7822
Epoch 58/100
35/35 [==============================] - 0s 1ms/step - loss: 1.5481 - accuracy: 0.7514
Epoch 59/100
35/35 [==============================] - 0s 1ms/step - loss: 1.6088 - accuracy: 0.7595
Epoch 60/100
35/35 [==============================] - 0s 864us/step - loss: 0.9035 - accuracy: 0.7931
Epoch 61/100
35/35 [==============================] - 0s 719us/step - loss: 2.0760 - accuracy: 0.7423
Epoch 62/100
35/35 [==============================] - 0s 747us/step - loss: 1.2916 - accuracy: 0.7677
Epoch 63/100
35/35 [==============================] - 0s 859us/step - loss: 1.0401 - accuracy: 0.7668
Epoch 64/100
35/35 [==============================] - 0s 812us/step - loss: 1.2214 - accuracy: 0.7840
Epoch 65/100
35/35 [==============================] - 0s 720us/step - loss: 0.7720 - accuracy: 0.7813
Epoch 66/100
35/35 [==============================] - 0s 737us/step - loss: 1.1204 - accuracy: 0.7722
Epoch 67/100
35/35 [==============================] - 0s 751us/step - loss: 1.4987 - accuracy: 0.7768
Epoch 68/100
35/35 [==============================] - 0s 718us/step - loss: 0.9161 - accuracy: 0.7922
Epoch 69/100
35/35 [==============================] - 0s 768us/step - loss: 2.2794 - accuracy: 0.7514
Epoch 70/100
35/35 [==============================] - 0s 772us/step - loss: 1.3872 - accuracy: 0.7768
Epoch 71/100
35/35 [==============================] - 0s 724us/step - loss: 0.8926 - accuracy: 0.7877
Epoch 72/100
35/35 [==============================] - 0s 748us/step - loss: 0.5626 - accuracy: 0.8330
Epoch 73/100
35/35 [==============================] - 0s 738us/step - loss: 2.9094 - accuracy: 0.7541
Epoch 74/100
35/35 [==============================] - 0s 714us/step - loss: 2.7208 - accuracy: 0.7450
Epoch 75/100
35/35 [==============================] - 0s 729us/step - loss: 3.7597 - accuracy: 0.7514
Epoch 76/100
35/35 [==============================] - 0s 764us/step - loss: 1.2033 - accuracy: 0.7895
Epoch 77/100
35/35 [==============================] - 0s 853us/step - loss: 1.9837 - accuracy: 0.7505
Epoch 78/100
35/35 [==============================] - 0s 950us/step - loss: 1.0956 - accuracy: 0.7822
Epoch 79/100
35/35 [==============================] - 0s 923us/step - loss: 1.2944 - accuracy: 0.7804
Epoch 80/100
35/35 [==============================] - 0s 713us/step - loss: 1.8372 - accuracy: 0.7650
Epoch 81/100

35/35 [==============================] - 0s 742us/step - loss: 1.5255 - accuracy: 0.7368
Epoch 82/100
35/35 [==============================] - 0s 726us/step - loss: 0.9524 - accuracy: 0.7849
Epoch 83/100
35/35 [==============================] - 0s 772us/step - loss: 0.9824 - accuracy: 0.8094
Epoch 84/100
35/35 [==============================] - 0s 787us/step - loss: 1.2316 - accuracy: 0.7677
Epoch 85/100
35/35 [==============================] - 0s 747us/step - loss: 2.0699 - accuracy: 0.7514
Epoch 86/100
35/35 [==============================] - 0s 745us/step - loss: 1.8677 - accuracy: 0.7514
Epoch 87/100
35/35 [==============================] - 0s 738us/step - loss: 1.5163 - accuracy: 0.7659
Epoch 88/100
35/35 [==============================] - 0s 724us/step - loss: 0.7154 - accuracy: 0.8258
Epoch 89/100
35/35 [==============================] - 0s 752us/step - loss: 1.0728 - accuracy: 0.7922
Epoch 90/100
35/35 [==============================] - 0s 731us/step - loss: 1.3638 - accuracy: 0.7786
Epoch 91/100
35/35 [==============================] - 0s 707us/step - loss: 1.9586 - accuracy: 0.7677
Epoch 92/100
35/35 [==============================] - 0s 734us/step - loss: 0.6477 - accuracy: 0.8094
Epoch 93/100
35/35 [==============================] - 0s 724us/step - loss: 2.5903 - accuracy: 0.7550
Epoch 94/100
35/35 [==============================] - 0s 790us/step - loss: 0.6247 - accuracy: 0.8240
Epoch 95/100
35/35 [==============================] - 0s 798us/step - loss: 0.7866 - accuracy: 0.8049
Epoch 96/100
35/35 [==============================] - 0s 730us/step - loss: 0.6057 - accuracy: 0.8294
Epoch 97/100
35/35 [==============================] - 0s 731us/step - loss: 1.6026 - accuracy: 0.7804
Epoch 98/100
35/35 [==============================] - 0s 756us/step - loss: 0.4861 - accuracy: 0.8494
Epoch 99/100
35/35 [==============================] - 0s 742us/step - loss: 0.7397 - accuracy: 0.8240
Epoch 100/100
35/35 [==============================] - 0s 728us/step - loss: 2.7270 - accuracy: 0.7704

In [11]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 3.1003 - accuracy: 0.8668 - 92ms/epoch - 8ms/step
Loss: 3.1003377437591553, Accuracy: 0.866847813129425

In [12]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [13]:
# Train the model 
fit_model = nn.fit(X_train_scaled, y_train, epochs=50) 
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
35/35 [==============================] - 0s 765us/step - loss: 0.6804 - accuracy: 0.5209
Epoch 2/50
35/35 [==============================] - 0s 797us/step - loss: 0.5978 - accuracy: 0.7051
Epoch 3/50
35/35 [==============================] - 0s 820us/step - loss: 0.5373 - accuracy: 0.7922
Epoch 4/50
35/35 [==============================] - 0s 812us/step - loss: 0.4887 - accuracy: 0.8194
Epoch 5/50
35/35 [==============================] - 0s 833us/step - loss: 0.4524 - accuracy: 0.8240
Epoch 6/50
35/35 [==============================] - 0s 806us/step - loss: 0.4257 - accuracy: 0.8285
Epoch 7/50
35/35 [==============================] - 0s 850us/step - loss: 0.4058 - accuracy: 0.8303
Epoch 8/50
35/35 [==============================] - 0s 786us/step - loss: 0.3905 - accuracy: 0.8312
Epoch 9/50
35/35 [==============================] - 0s 769us/step - loss: 0.3775 - accuracy: 0.8312
Epoch 10/50
35/35 [==============================] - 0s 791us/step - loss: 0.3673 - accuracy: 0.8321
Epoch 11/50
35/35 [==============================] - 0s 846us/step - loss: 0.3579 - accuracy: 0.8348
Epoch 12/50
35/35 [==============================] - 0s 890us/step - loss: 0.3507 - accuracy: 0.8385
Epoch 13/50
35/35 [==============================] - 0s 850us/step - loss: 0.3424 - accuracy: 0.8448
Epoch 14/50
35/35 [==============================] - 0s 876us/step - loss: 0.3353 - accuracy: 0.8494
Epoch 15/50
35/35 [==============================] - 0s 878us/step - loss: 0.3288 - accuracy: 0.8548
Epoch 16/50
35/35 [==============================] - 0s 804us/step - loss: 0.3230 - accuracy: 0.8621
Epoch 17/50
35/35 [==============================] - 0s 885us/step - loss: 0.3163 - accuracy: 0.8666
Epoch 18/50
35/35 [==============================] - 0s 877us/step - loss: 0.3105 - accuracy: 0.8711
Epoch 19/50
35/35 [==============================] - 0s 810us/step - loss: 0.3037 - accuracy: 0.8784
Epoch 20/50
35/35 [==============================] - 0s 826us/step - loss: 0.2982 - accuracy: 0.8802
Epoch 21/50
35/35 [==============================] - 0s 841us/step - loss: 0.2916 - accuracy: 0.8829
Epoch 22/50
35/35 [==============================] - 0s 754us/step - loss: 0.2873 - accuracy: 0.8829
Epoch 23/50
35/35 [==============================] - 0s 861us/step - loss: 0.2810 - accuracy: 0.8829
Epoch 24/50
35/35 [==============================] - 0s 827us/step - loss: 0.2753 - accuracy: 0.8875
Epoch 25/50
35/35 [==============================] - 0s 775us/step - loss: 0.2703 - accuracy: 0.8893
Epoch 26/50
35/35 [==============================] - 0s 1ms/step - loss: 0.2650 - accuracy: 0.8875
Epoch 27/50
35/35 [==============================] - 0s 980us/step - loss: 0.2605 - accuracy: 0.8911
Epoch 28/50
35/35 [==============================] - 0s 856us/step - loss: 0.2565 - accuracy: 0.8902
Epoch 29/50
35/35 [==============================] - 0s 922us/step - loss: 0.2527 - accuracy: 0.8947
Epoch 30/50
35/35 [==============================] - 0s 916us/step - loss: 0.2483 - accuracy: 0.8938
Epoch 31/50
35/35 [==============================] - 0s 852us/step - loss: 0.2441 - accuracy: 0.8966
Epoch 32/50
35/35 [==============================] - 0s 879us/step - loss: 0.2406 - accuracy: 0.8966
Epoch 33/50
35/35 [==============================] - 0s 819us/step - loss: 0.2367 - accuracy: 0.8984
Epoch 34/50
35/35 [==============================] - 0s 884us/step - loss: 0.2331 - accuracy: 0.8984
Epoch 35/50
35/35 [==============================] - 0s 998us/step - loss: 0.2302 - accuracy: 0.9029
Epoch 36/50
35/35 [==============================] - 0s 964us/step - loss: 0.2275 - accuracy: 0.9020
Epoch 37/50
35/35 [==============================] - 0s 966us/step - loss: 0.2240 - accuracy: 0.9029
Epoch 38/50
35/35 [==============================] - 0s 981us/step - loss: 0.2214 - accuracy: 0.9056
Epoch 39/50
35/35 [==============================] - 0s 1ms/step - loss: 0.2195 - accuracy: 0.9083
Epoch 40/50
35/35 [==============================] - 0s 1ms/step - loss: 0.2177 - accuracy: 0.9120
Epoch 41/50
35/35 [==============================] - 0s 983us/step - loss: 0.2145 - accuracy: 0.9093
Epoch 42/50
35/35 [==============================] - 0s 972us/step - loss: 0.2121 - accuracy: 0.9120
Epoch 43/50
35/35 [==============================] - 0s 765us/step - loss: 0.2099 - accuracy: 0.9111
Epoch 44/50
35/35 [==============================] - 0s 888us/step - loss: 0.2075 - accuracy: 0.9120
Epoch 45/50
35/35 [==============================] - 0s 873us/step - loss: 0.2061 - accuracy: 0.9111
Epoch 46/50
35/35 [==============================] - 0s 851us/step - loss: 0.2048 - accuracy: 0.9156
Epoch 47/50
35/35 [==============================] - 0s 918us/step - loss: 0.2021 - accuracy: 0.9102
Epoch 48/50
35/35 [==============================] - 0s 845us/step - loss: 0.1998 - accuracy: 0.9165
Epoch 49/50
35/35 [==============================] - 0s 792us/step - loss: 0.1982 - accuracy: 0.9111
Epoch 50/50
35/35 [==============================] - 0s 804us/step - loss: 0.1965 - accuracy: 0.9156
12/12 - 0s - loss: 0.3579 - accuracy: 0.8587 - 71ms/epoch - 6ms/step
Loss: 0.3578794598579407, Accuracy: 0.8586956262588501

### SVM and deep learning models both achieved a predictive accuracy of around 87%.